databases:
  - name: kitobxon-db
    databaseName: kitobxon
    user: kitobxon_user
    plan: free # Bepul reja
    region: singapore # Yoki frankfurt (Osiyo/Yevropa uchun tezroq)

services:
  - type: web
    name: kitobxon-backend
    env: node
    plan: free # Bepul reja
    buildCommand: cd backend && npm install
    startCommand: cd backend && node seed.js && node src/app.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kitobxon-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true # Xavfsiz random parol yaratadi
      - key: NODE_ENV
        value: production
    autoDeploy: true
